version: '3.3'
services:
  django-ha-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASS}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  django-ha:
      build: ./src
      command: /bin/sh /code/docker-entrypoint.sh
      environment:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DJ_USER: ${DJ_USER}
        DJ_PASS: ${DJ_PASS}
        DJ_MAIL: ${DJ_MAIL}
      volumes:
          - ./src:/code
      ports:
          - "8000:8000"
      depends_on:
          - django-ha-db

# Names our volume
volumes:
  my-db:
